ALTER TABLE "purchase_payments" ADD COLUMN "target" text DEFAULT 'supplier' NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_receipt_lines" ADD COLUMN "shipping_amount" numeric(18, 2) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_receipts" ADD COLUMN "shipping_amount" numeric(18, 2) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_receipts" ADD COLUMN "shipping_supplier_id" uuid;--> statement-breakpoint
ALTER TABLE "purchase_receipts" ADD COLUMN "shipping_supplier_name" varchar(160);--> statement-breakpoint
ALTER TABLE "purchase_receipts" ADD COLUMN "shipping_allocation" text DEFAULT 'value' NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_receipts" ADD COLUMN "shipping_paid_amount" numeric(18, 2) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_receipts" ADD CONSTRAINT "purchase_receipts_shipping_supplier_id_suppliers_id_fk" FOREIGN KEY ("shipping_supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_payments" ADD CONSTRAINT "payment_target_valid" CHECK ("purchase_payments"."target" in ('supplier','shipping'));--> statement-breakpoint
ALTER TABLE "purchase_receipt_lines" ADD CONSTRAINT "receipt_line_shipping_valid" CHECK ("purchase_receipt_lines"."shipping_amount" >= 0 and ("purchase_receipt_lines"."shipping_amount"=0 or "purchase_receipt_lines"."line_total" is not null));--> statement-breakpoint
ALTER TABLE "purchase_receipts" ADD CONSTRAINT "receipt_shipping_valid" CHECK ("purchase_receipts"."shipping_amount" >= 0 and "purchase_receipts"."shipping_paid_amount" >= 0 and "purchase_receipts"."shipping_allocation" in ('value','manual') and (("purchase_receipts"."shipping_amount"=0 and "purchase_receipts"."shipping_supplier_id" is null and "purchase_receipts"."shipping_supplier_name" is null and "purchase_receipts"."shipping_paid_amount"=0) or ("purchase_receipts"."shipping_amount">0 and "purchase_receipts"."shipping_supplier_id" is not null and "purchase_receipts"."shipping_supplier_name" is not null and "purchase_receipts"."total_amount" is not null)));--> statement-breakpoint
ALTER TABLE "purchase_receipts" ADD CONSTRAINT "receipt_shipping_paid_limit" CHECK (("purchase_receipts"."shipping_supplier_id" = "purchase_receipts"."supplier_id" and "purchase_receipts"."shipping_paid_amount"=0) or ("purchase_receipts"."shipping_supplier_id" is distinct from "purchase_receipts"."supplier_id" and "purchase_receipts"."shipping_paid_amount" <= "purchase_receipts"."shipping_amount"));